### PR TITLE
Added Spanish Translation

### PR DESCRIPTION
**Pull request by DeltaVeintiuno**
I added the Spanish translation. If there is an error, please let me know. I am new on this.

### CODE REVIEW

**Comment by DeltaVeintiuno** [comment]
I notice the template version was out of date, going to fix it

**Comment by DeltaVeintiuno** [comment]
It is updated now. Just want to let you know, in Spanish Reset and Reboot their translation is the same, "Reiniciar".

**Comment by fsobolev** [comment]
Ah, I completely forgot about the template, sorry. I'm not home now, so I will update template and make a new release with you translation later tonight. But before that...

> in Spanish Reset and Reboot their translation is the same, "Reiniciar".

Please change this. Feel free to use multiple words (the reset timer button should scale if you use multiple words in it, don't worry). If you use GNOME, check what word it uses for reboot action in the system menu, maybe it's something different. Just make it less confusing somehow :)
Thanks! ❤️ 

**Edit:** You can also translate the reset button as you would translate "clear" if it's not confusing in Spanish. At least in Russian it would be more or less acceptable.

**Comment by DeltaVeintiuno** [comment]
All right, I found another word. But it's weird, because in GNOME Clock is the same word as reboot. However it's fixed now.

**Comment by DeltaVeintiuno** [comment]
> Edit: You can also translate the reset button as you would translate "clear" if it's not confusing in Spanish. At least in Russian it would be more or less acceptable.

Yeah, it means something similar to clear.

**Comment by fsobolev** [comment]
Looks good to me, thank you! 😊

**Comment by DeltaVeintiuno** [comment]
>Looks good to me, thank you! blush

It is a pleasure.

**Pull request merged**
