### PR TITLE
Added Brazilian Portuguese Translation

### PR DESCRIPTION
**Pull request by plasmus777**
I was browsing through flathub and found this project. Since i like the app, here is a new translation for you: it adds brazilian portuguese (pt_BR) support.

### CODE REVIEW

**Comment by fsobolev** [comment]
Thank you 😊 I don't plan to make a new release until I implement new feature requested in #18, and it will add some strings. That's why I will keep this PR opened for now, so you will not need to open new PR when new strings will be added.
Also:
```
msgid "Time Switch"
msgstr "Cronômetro"
```

AFAIK there are different conventions on whether should apps' names be translated/transliterated. For example, in Hindi they are transliterated, and in Russian they are neither translated nor transliterated. Please look at other apps (that are **not** GNOME core apps) that have Brazilian Portuguese translations and change the app name translation if needed.

**Comment by plasmus777** [comment]
Hello and thanks for the answer,
The usual convention for naming applications is leaving the name unchanged or tweaking a few words. However, sometimes an object can have a name in english that simply does not have an exact meaning in portuguese (such as "time switch" -> "timer"/"temporizador"/interruptor temporizador"/"_cronômetro_"/...), creating the issue of not being very easy to detect/find.
**I will revert the name translation for now in order to keep the application related to the project**.

**Comment by fsobolev** [comment]
Two new strings was added, please update translation

**Comment by fsobolev** [comment]
Thank you 😊

**Pull request merged**
