### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by ghost**
Mostly translation related changes. Also corrects build path.

### CODE REVIEW

**Comment by fsobolev** [comment]
Thank you :blush: I don't plan to make a new release until I implement new feature requested in #18, and it will add some strings. That's why I will keep this PR opened for now, so you will not need to open new PR when new strings will be added.

**Comment by fsobolev** [comment]
Two new strings was added, please update translation

**Comment by ghost** [comment]
@fsobolev No conflict. Could you merge it.

**Comment by fsobolev** [comment]
Thank you! 😊

**Pull request merged**
